name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  frontend-lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Validate HTML
      run: |
        cd frontend
        npm install -g html-validate
        html-validate index.html
        html-validate index2.html

    - name: Check Assets
      run: |
        cd frontend
        ls -l assets/
        echo "Vérification du contenu des assets"

    - name: Analyze Forms
      run: |
        cd frontend
        ls -l forms/
        echo "Vérification du contenu des formulaires"
