name: Full Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Prepare Backend Deployment
      run: |
        cd backend
        pip install -r requirements.txt
        
        # Création d'un artifact du backend
        tar -czvf backend-artifact.tar.gz .

    - name: Upload Backend Artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-deployment
        path: backend/backend-artifact.tar.gz
        retention-days: 5

  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Frontend
      run: |
        cd frontend
        # Création d'un artifact du frontend
        tar -czvf frontend-artifact.tar.gz .

    - name: Upload Frontend Artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-deployment
        path: frontend/frontend-artifact.tar.gz
        retention-days: 5
